**Topic 1 : Creating First Array**


In [4]:
import numpy as np
arr=np.array([2,3,4,5])
print(arr)

[2 3 4 5]


**Topic 2 : Creating 1D Array**

In [6]:
name=np.array(["shubham","Dhar","VCP","DSP"])
print(name)
print(type(name))

['shubham' 'Dhar' 'VCP' 'DSP']
<class 'numpy.ndarray'>


**Topic 3 : Different Ways to Create 1D Array**

In [7]:
arr1=np.array([1,2,3,4])
arr2=np.array((8,7,6,5))
print(arr1)
print(arr2)

[1 2 3 4]
[8 7 6 5]


**Topic 4 : Check Dimension of Array**

In [8]:
arr=np.array((2,3,4,5))
print(arr.ndim)

1


**Topic 5 : Creating 2D Array**

In [ ]:
arr=np.array([
    [10,20,30],[40,50,60]
])

print(arr)
print(f"dimension: {arr.ndim}")


[[10 20 30]
 [40 50 60]]
dimension: 2


**Topic 6 : Creating 3D Array**

In [12]:
arr=np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
print(arr)
print(f"dimension: {arr.ndim}")


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimension: 3


**Topic 7 : Array Shape (shape)**

In [13]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.shape)

(2, 3)


**Topic 8 : Array Size (size)**

In [16]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(f"array size : {arr.size}")

array size : 6


**Topic 9: Data Type (dtype)**

In [17]:
arr1 = np.array([2,3,4,5])
arr2 = np.array((3,4,5))
print(arr1.dtype)
print(arr2.dtype)

int64
int64


**Topic 10 : Item Size (itemsize)**

In [18]:

arr = np.array([10, 20, 30, 40])

print(arr.nbytes)

32


**Rivision**

In [19]:

arr = np.array([
    [5, 10, 15],
    [20, 25, 30]
])

print("Array:")
print(arr)

print("\nDimension :", arr.ndim)
print("Shape     :", arr.shape)
print("Size      :", arr.size)
print("Data Type :", arr.dtype)
print("Item Size :", arr.itemsize)
print("Total Memory :", arr.nbytes)

Array:
[[ 5 10 15]
 [20 25 30]]

Dimension : 2
Shape     : (2, 3)
Size      : 6
Data Type : int64
Item Size : 8
Total Memory : 48
