**1. Positive Indexing**

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

10
20
30
40
50


**2. Negative Indexing**

In [3]:
arr = np.array([10,20,30,40,50])

print(arr[-1])
print(arr[-2])
print(arr[-3])
print(arr[-4])
print(arr[-5])

50
40
30
20
10


**3. 1D Array Slicing**

In [ ]:
arr = np.array([10,20,30,40,50,60,70])
print(arr[1:5])

print(arr[:4])

print(arr[3:])

print(arr[:])

print(arr[::2])

print(arr[::-1])

[20 30 40 50]
[10 20 30 40]
[40 50 60 70]
[10 20 30 40 50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]


**4. 2D Array Indexing**

In [6]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[0,0])

print(arr[1,2])

print(arr[2,1])

10
60
80


**5. 2D Array Slicing**

In [ ]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[:,1])  # all ,column1

print(arr[1,:])  # second row

print(arr[0:2,1:3])  #  (0,1)Rows ,(1,2)Columns

[20 50 80]
[40 50 60]
[[20 30]
 [50 60]]


**6. 3D Array Indexing**

In [ ]:

arr = np.array([
                    [
                        [1,2],
                        [3,4]
                    ],
                    [
                        [5,6],
                        [7,8]
                    ]
                ])

print(arr[0,0,1])  # layer 0,row 0,column 1

print(arr[1,1,0])   # layer 1, row 1, column 0

2
7


**7. Boolean Indexing**

In [9]:

arr = np.array([10,20,30,40,50])
print(arr>30)
print(arr[arr>30])


[False False False  True  True]
[40 50]


**8. Fancy Indexing**

In [ ]:

arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])  # Sirf selected indexes return honge.

[10 30 50]


**9. Modify Elements**

In [11]:

arr = np.array([10,20,30,40])
arr[1]=100

print(arr)

[ 10 100  30  40]


**10. Complete Practice Program**

In [12]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print("Array")
print(arr)
print("\nFirst Element :",arr[0,0])
print("\nLast Element :",arr[-1,-1])
print("\nSecond Column")
print(arr[:,1])
print("\nLast Row")
print(arr[-1])
print("\nSlice")
print(arr[0:2,1:3])

Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]

First Element : 10

Last Element : 90

Second Column
[20 50 80]

Last Row
[70 80 90]

Slice
[[20 30]
 [50 60]]
