**1. Arithmetic Operations**

In [3]:
import numpy as np

arr1 = np.array([10, 20, 30])

arr2 = np.array([1, 2, 3])

print("Addition")
print(arr1 + arr2)

print()

print("Subtraction")
print(arr1 - arr2)

print()

print("Multiplication")
print(arr1 * arr2)

print()

print("Division")
print(arr1 / arr2)

print()

print("Floor Division")
print(arr1 // arr2)

print()

print("Modulus")
print(arr1 % arr2)

print()

print("Power")
print(arr1 ** arr2)

Addition
[11 22 33]

Subtraction
[ 9 18 27]

Multiplication
[10 40 90]

Division
[10. 10. 10.]

Floor Division
[10 10 10]

Modulus
[0 0 0]

Power
[   10   400 27000]


**2. Comparison Operations**

In [ ]:
arr = np.array([10,20,30,40,50])

print(arr>25)

print(arr<25)

print(arr==30)

print(arr!=30)

print(arr>=30)

print(arr<=30)

[False False  True  True  True]
[ True  True False False False]
[False False  True False False]
[ True  True False  True  True]
[False False  True  True  True]
[ True  True  True False False]


**3. Universal Functions (ufunc)**

In [5]:
arr=np.array([1,4,9,16,25])

print(np.sqrt(arr))

print(np.square(arr))

print(np.abs([-10,20,-30]))

print(np.power(arr,2))

[1. 2. 3. 4. 5.]
[  1  16  81 256 625]
[10 20 30]
[  1  16  81 256 625]


**4. Mathematical Functions**

In [ ]:
arr=np.array([10,20,30,40])

print(np.min(arr))

print(np.max(arr))

print(np.sum(arr))

print(np.prod(arr)) #10×20×30×40

10
40
100
240000


**5. Statistical Functions**

In [ ]:
arr=np.array([10,20,30,40,50])

print(np.mean(arr))  # Average

print(np.median(arr))  # Middle Value

print(np.std(arr))  # Data kitna spread hai.

print(np.var(arr))  # Standard deviation ka square.

30.0
30.0
14.142135623730951
200.0


6. Aggregate Functions

In [ ]:
arr=np.array([
[10,20,30],
[40,50,60]
])

print(arr.sum())
print(arr.sum(axis=0))  # Column Wise
print(arr.sum(axis=1))  # Row Wise

210
[50 70 90]
[ 60 150]


**7. Broadcasting**

In [10]:
arr=np.array([10,20,30])

print(arr+5)

print(arr*2)

[15 25 35]
[20 40 60]


**8. Vectorization**  (Vectorization = without loop fast computation)

In [11]:
arr=np.array([1,2,3,4,5])

result=arr*10

print(result)

[10 20 30 40 50]


**9. Complete Practice Program**

In [12]:
arr=np.array([10,20,30,40,50])

print("Addition :",arr+10)

print("Square :",np.square(arr))

print("Mean :",np.mean(arr))

print("Maximum :",np.max(arr))

print("Minimum :",np.min(arr))

print("Reverse :",arr[::-1])

Addition : [20 30 40 50 60]
Square : [ 100  400  900 1600 2500]
Mean : 30.0
Maximum : 50
Minimum : 10
Reverse : [50 40 30 20 10]
