**📚 Topics Covered**
1. reshape()
2. flatten()
3. ravel()
4. transpose()
5. resize()
6. concatenate()
7. split()
8. hstack()
9. vstack()
10. column_stack()
11. Complete Practice Program


**1. reshape()**

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)  # 2row,3col

print(new_arr)

[[1 2 3]
 [4 5 6]]


**2. flatten()**  
2D Array ko, 1D Array me convert karta hai.
Notes:
Copy return karta hai.
Original Array change nahi hota.

In [3]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

new_arr = arr.flatten()

print(new_arr)

[1 2 3 4 5 6]


**3. ravel()**

In [ ]:
arr = np.array([
    [10,20],
    [30,40]
])
new_arr = arr.ravel() # Ye bhi flatten ki tarah 1D Array banata hai.
print(new_arr)

[10 20 30 40]


**4. transpose()**

In [7]:
arr1 = np.array([
    [10,20],
    [30,40]
])

print(arr1.T)

print()
arr2 = np.array([
    [2,3],
    [4,5]
])

print(arr2.transpose())

[[10 30]
 [20 40]]

[[2 4]
 [3 5]]


**5. resize()**

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])

arr.resize((2,2))

print(arr)

None


**6. concatenate()**

In [13]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

result = np.concatenate((arr1,arr2))

print(result)

[1 2 3 4 5 6]


**7. split()**

In [18]:
import numpy as np

arr1 = np.array([10,20,30,40,50,60])
result1 = np.split(arr1,2)
print(result1)
print()
arr2 = np.array([10,20,30,40,50,60])
result2 = np.split(arr2,2)
print(result2)

[array([10, 20, 30]), array([40, 50, 60])]

[array([10, 20, 30]), array([40, 50, 60])]


**8. hstack()**

In [19]:
arr1 = np.array([1,2])

arr2 = np.array([3,4])

print(np.hstack((arr1,arr2)))  # Horizontal Stack

[1 2 3 4]


**9. vstack()**

In [20]:
arr1 = np.array([1,2])

arr2 = np.array([3,4])

print(np.vstack((arr1,arr2)))  # vertical Stack

[[1 2]
 [3 4]]


**10. column_stack()**

In [ ]:
arr1 = np.array([1,2,3,4])

arr2 = np.array([5,6,7,8])

print(np.column_stack((arr1,arr2)))  # column Stack

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


**11. Complete Practice Program**

In [22]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print("Original")
print(arr)

print()

print("Reshape")
print(arr.reshape(2,3))

print()

print("Flatten")
print(arr.reshape(2,3).flatten())

print()

print("Transpose")
print(arr.reshape(2,3).T)

print()

print("Concatenate")

arr2 = np.array([7,8,9])

print(np.concatenate((arr[:3],arr2)))

print()

print("Split")

print(np.split(arr,3))

Original
[1 2 3 4 5 6]

Reshape
[[1 2 3]
 [4 5 6]]

Flatten
[1 2 3 4 5 6]

Transpose
[[1 4]
 [2 5]
 [3 6]]

Concatenate
[1 2 3 7 8 9]

Split
[array([1, 2]), array([3, 4]), array([5, 6])]
