**Topics Covered**
1. np.random.rand()
2. np.random.randn()
3. np.random.randint()
4. np.random.random()
5. np.random.choice()
6. np.random.shuffle()
7. np.random.permutation()
8. np.random.seed()
9. Random Sampling
10. Complete Practice Program


**1. np.random.rand()**

In [2]:
import numpy as np
arr=np.random.rand(5)
print(arr)

[0.1623741  0.46494835 0.77436964 0.70218417 0.84013648]


**2. np.random.randn()**

In [3]:
arr = np.random.randn(5)

print(arr)

[-0.52866695  0.47076887 -0.35883309  0.12975549  2.49756205]


**3. np.random.randint()**

In [ ]:
arr=np.random.randint(1,100,10)
print(arr)
# Start = 1
# Stop = 100
# Size = 10

[21 59 37  8  4 25 57 97 72 56]


'Start = 1\n\nStop = 100\n\nSize = 10'

**4. np.random.random()**

In [6]:
arr = np.random.random(5)

print(arr)

[0.37151144 0.11639797 0.76774034 0.22101655 0.24790348]


**5. np.random.choice()**

In [11]:
arr = np.random.choice([10,20,40,50])

print(arr)

40


**6. np.random.shuffle()**

In [14]:
arr=np.array([10,20,30,40,50])
np.random.shuffle(arr)
print(arr)

[20 40 10 50 30]


**7. np.random.permutation()**

In [ ]:
arr=np.array([10,20,30,40])
new_arr=np.random.permutation(arr) #Permutation ek shuffled copy return karta hai.
print(new_arr)
print(arr)

[40 20 30 10]
[10 20 30 40]


**8. np.random.seed()**

In [17]:
np.random.seed(100)

print(np.random.randint(1,100,5))

[ 9 25 68 88 80]


**9. Random Sampling**

In [18]:
data = np.array([10,20,30,40,50,60,70])

sample = np.random.choice(data,3)

print(sample)

[10 30 70]


**10. Complete Practice Program**

In [19]:
print("Random Float")

print(np.random.rand(5))

print()

print("Random Integer")

print(np.random.randint(1,100,5))

print()

print("Random Choice")

print(np.random.choice([100,200,300,400]))

print()

arr = np.array([1,2,3,4,5])

print("Shuffle")

np.random.shuffle(arr)

print(arr)

print()

print("Permutation")

print(np.random.permutation(arr))

Random Float
[0.15671108 0.18646718 0.21010774 0.4527399  0.87014264]

Random Integer
[16 61 59 17 10]

Random Choice
200

Shuffle
[2 5 1 4 3]

Permutation
[2 1 4 3 5]
