**Topics Covered**
1. Dot Product
2. Matrix Multiplication
3. matmul()
4. transpose()
5. Determinant
6. Inverse Matrix
7. Trace
8. Rank
9. Eigen Values
10. Eigen Vectors
11. Complete Practice Program

**1. Dot Product**

In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result= np.dot(arr1,arr2)
print(result)

# Dot Product = Multiplication + Addition
# ML Algorithms me bahut use hota hai.

32


**2. Matrix Multiplication**

In [14]:


A= np.array([
    [1,2],
    [3,4]
])

B=np.array([
    [5,6],
    [7,8]
])

print(A@B)  # @ is  Matrix Multiplication Operator



[[19 22]
 [43 50]]


**3. matmul()**

In [ ]:
result = np.matmul(A,B)  # Same kaam karta hai A@B jaise
print(result)

[[19 22]
 [43 50]]


**4. Transpose**

In [15]:
A= np.array([
    [1,2],
    [3,4]
])
print(A.T)

[[1 3]
 [2 4]]


**5. Determinant**

In [16]:
A= np.array([
    [1,2],
    [3,4]
])
det = np.linalg.det(A)  
print(det)

# ad-bc  formula

-2.0000000000000004


**6. Inverse Matrix**

In [17]:
A= np.array([
    [1,2],
    [3,4]
])
inverse = np.linalg.inv(A)  #  A⁻¹
print(inverse)

# Notes
# Inverse sirf
# Square Matrix
# AND
# Determinant ≠ 0
# par hi possible hai.

[[-2.   1. ]
 [ 1.5 -0.5]]


**7. Trace**

In [18]:
A= np.array([
    [1,2],
    [3,4]
])
print(np.trace(A))  # trace => Diagonal Sum

5


**8. Rank**

In [19]:
A= np.array([
    [1,2],
    [3,4]
])

print(np.linalg.matrix_rank(A))

2


**9. Eigen Values**

In [20]:
A= np.array([
    [1,2],
    [3,4]
])

values,vectors=np.linalg.eig(A)
print(values)

[-0.37228132+0.j  5.37228132+0.j]


**10. Eigen Vectors**

In [21]:
A= np.array([
    [1,2],
    [3,4]
])

print(vectors)

[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


**11. Complete Practice Program**

In [24]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print("Dot Product")

print(np.dot(np.array([1,2]),np.array([3,4])))

print()

print("Matrix Multiplication")

print(A@B)

print()

print("Transpose")

print(A.T)

print()

print("Determinant")

print(np.linalg.det(A))

print()

print("Inverse")

print(np.linalg.inv(A))

print()

print("Trace")

print(np.trace(A))

print()

print("Rank")

print(np.linalg.matrix_rank(A))

print()

print("Eigen Values")

values,vectors=np.linalg.eig(A)

print(values)

print()

print("Eigen Vectors")

print(vectors)

Dot Product
11

Matrix Multiplication
[[19 22]
 [43 50]]

Transpose
[[1 3]
 [2 4]]

Determinant
-2.0000000000000004

Inverse
[[-2.   1. ]
 [ 1.5 -0.5]]

Trace
5

Rank
2

Eigen Values
[-0.37228132+0.j  5.37228132+0.j]

Eigen Vectors
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]
