**Topics Covered**
1. Save Array (.npy)
2. Load Array (.npy)
3. Save Multiple Arrays (.npz)
4. Load Multiple Arrays (.npz)
5. Save Array to CSV
6. Load Array from CSV
7. Save Array to Text File
8. Load Text File
9. Complete Practice Program
10. Notes

**1. Save Array (.npy)**

In [2]:
import numpy as np

In [1]:

import numpy as np
arr = np.array([10, 20, 30, 40, 50])

np.save("student_marks.npy", arr)

print("Array Saved Successfully")

Array Saved Successfully


**2. Load Array (.npy)**

In [3]:
loaded_arry=np.load("student_marks.npy")
print(loaded_arry)

[10 20 30 40 50]


**3. Save Multiple Arrays (.npz)**

In [4]:
marks = np.array([80, 75, 90])

ages = np.array([21, 22, 20])

np.savez("students.npz", marks=marks, ages=ages)

print("Multiple Arrays Saved")

Multiple Arrays Saved


**4. Load Multiple Arrays (.npz)**

In [6]:
data =np.load("students.npz")
print(data["marks"])
print(data["ages"])

[80 75 90]
[21 22 20]


**5. Save Array to CSV**

In [ ]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])

np.savetxt("marks.csv", arr, delimiter="," , fmt="%d")
print("CSV File Saved")

# Notes:
# CSV
# ↓
# Excel
# ↓
# Pandas
# ↓
# Data Analysis
# Sab isi format ko use karte hain.

CSV File Saved


**6. Load CSV File**

In [3]:
data = np.loadtxt("marks.csv", delimiter=",")
print(data)

[[10. 20. 30.]
 [40. 50. 60.]]


**7. Save Text File**

In [4]:
arr = np.array([100,200,300,400])

np.savetxt("numbers.txt", arr)

print("Text File Saved")

Text File Saved


**8. Load Text File**

In [5]:
data = np.loadtxt("numbers.txt")
print(data)

[100. 200. 300. 400.]


**9. Complete Practice Program**

In [6]:
# Create Array
arr = np.array([10,20,30,40,50])

# Save
np.save("demo.npy", arr)

# Load
data = np.load("demo.npy")

print("Loaded Array")

print(data)

print()

# CSV

np.savetxt("demo.csv", arr, delimiter=",", fmt="%d")

csv_data = np.loadtxt("demo.csv", delimiter=",")

print("CSV Data")

print(csv_data)

print()

# Multiple Arrays

a = np.array([1,2,3])

b = np.array([4,5,6])

np.savez("demo.npz", first=a, second=b)

files = np.load("demo.npz")

print(files["first"])

print(files["second"])

Loaded Array
[10 20 30 40 50]

CSV Data
[10. 20. 30. 40. 50.]

[1 2 3]
[4 5 6]
