In [1]:
# # Mathematics for Deep Learning

# ## Topics Covered

# - Scalar
# - Vector
# - Matrix
# - Tensor
# - Dot Product
# - Matrix Multiplication


Import Libraries

In [2]:
import numpy as np

import tensorflow as tf

**Scalar**

Scalar ek single numerical value hoti hai.

Examples

5

10

3.14

Temperature

Age

Scalar Example

In [ ]:
scalar = 10
print(scalar)
print(type(scalar))

# Explanation
# Scalar sirf ek value hoti hai.
# Deep Learning me learning rate, bias etc. scalar hote hain.

10
<class 'int'>


**Vector**

Vector ek 1-D collection hota hai.

Example

[2,4,6]

**Vector Example**

In [ ]:
vector = np.array(
    [2,4,6]
)
print(vector)
print(vector.shape)

# Explanation
# Vector multiple values ko ek line me store karta hai.
# Deep Learning me ek image ka row ya features vector ho sakte hain.

[2 4 6]
(3,)


**Matrix**

Matrix rows aur columns ka collection hota hai.

**Matrix Example**

In [ ]:
matrix = np.array(
    [
        [1,2],
        [3,4]
    ]
)

print(matrix)
print(matrix.shape)

[[1 2]
 [3 4]]
(2, 2)


**Tensor**

Tensor multi-dimensional data hota hai.

TensorFlow isi wajah se TensorFlow kehlata hai.

**Tensor Example**

In [6]:
tensor = tf.constant(
    [
        [1,2],
        [3,4]
    ]
)

print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


**Dot Product**

In [11]:
vector1 = np.array( [2,3] )

vector2 = np.array( [4,5])

dot = np.dot( vector1,vector2)

print(dot)

# Neural Network me har neuron Dot Product karta hai.

23


**Matrix Multiplication**

In [10]:
A = np.array( [ [1,2],[3,4] ] )

B = np.array( [ [5,6],[7,8] ] )

result = np.matmul(A,B)

print(result)
# Explanation
# Deep Learning me har layer Matrix Multiplication karti hai.
# Ye sabse important mathematical operation hai.

[[19 22]
 [43 50]]


Tensor Operations

In [9]:
tensor1 = tf.constant([1,2,3])
tensor2 = tf.constant([4,5,6])

print(tf.add(tensor1,tensor2))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


Real World Example

In [ ]:
# Image

# ↓

# Tensor

# ↓

# Neural Network

# ↓

# Matrix Multiplication

# ↓

# Prediction

# ChatGPT, Image Classification aur Face Recognition sab Tensor aur Matrix operations par kaam karte hain.

Aaj Humne Kya Sikha?

In [ ]:
# Scalar
# Vector
# Matrix
# Tensor
# Dot Product
# Matrix Multiplication
# Tensor Operations