In [1]:
# # TensorFlow Basics

# ## Topics Covered

# - What is TensorFlow?
# - Installation
# - Tensor
# - Constant
# - Variable
# - Data Types
# - Tensor Operations
# - GPU Check

In [2]:
# # What is TensorFlow?

# TensorFlow is an open-source Deep Learning framework developed by Google.

# It is used to build, train and deploy Deep Learning models.

# TensorFlow supports

# - CPU
# - GPU
# - TPU

# It is one of the most popular Deep Learning libraries.

Import TensorFlow

In [3]:
import tensorflow as tf

print("TensorFlow Version :", tf.__version__)

TensorFlow Version : 2.21.0


Create Your First Tensor

In [ ]:
tensor = tf.constant(10)
print(tensor)

# Explanation
# tf.constant() creates an immutable tensor.
# Once created, its value cannot be changed.

tf.Tensor(10, shape=(), dtype=int32)


Create Multiple Tensors

In [ ]:
tensor1 = tf.constant( [1,2,3,4,5] )

tensor2 = tf.constant( [ [1,2],[3,4] ] )

print(tensor1)
print(tensor2)

# Explanation

# 1-D Tensor
# ↓
# Vector

# 2-D Tensor
# ↓
# Matrix

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Tensor Data Types

In [ ]:
int_tensor = tf.constant(

    [1,2,3],

    dtype=tf.int32

)

float_tensor = tf.constant(

    [1.5,2.5,3.5],

    dtype=tf.float32

)

print(int_tensor.dtype)

print(float_tensor.dtype)

# Explanation
# TensorFlow supports many data types.
# Most commonly used
# int32
# float32
# bool
# string

<dtype: 'int32'>
<dtype: 'float32'>


Tensor Variables

In [ ]:
variable = tf.Variable(10)
print(variable)

variable.assign(20)
print(variable)

# Explanation
# tf.Variable() creates a mutable tensor.
# Variables are updated during model training.
# Weights and Biases are stored as Variables.

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>


Tensor Operations

In [11]:

a = tf.constant([1,3,5])
b = tf.constant([2,4,6])

print(tf.add(a,b))

print(tf.subtract(a,b))

print(tf.multiply(a,b))

print(tf.divide(a,b))

# Explanation
# TensorFlow provides built-in mathematical operations.
# Used internally while training Neural Networks.

tf.Tensor([ 3  7 11], shape=(3,), dtype=int32)
tf.Tensor([-1 -1 -1], shape=(3,), dtype=int32)
tf.Tensor([ 2 12 30], shape=(3,), dtype=int32)
tf.Tensor([0.5        0.75       0.83333333], shape=(3,), dtype=float64)


Check GPU Availability

In [14]:
print(

    "GPU Available :",

    tf.config.list_physical_devices("GPU")

)
# Explanation
# Checks whether TensorFlow can access a GPU.
# If the list is empty ([]), TensorFlow is running on CPU.

GPU Available : []


Tensor Shape

In [17]:
tensor = tf.constant(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(tensor.shape)
print(tf.rank(tensor))

# Explanation
# shape
# ↓
# Number of rows and columns.
# rank
# ↓
# Number of dimensions.

(2, 3)
tf.Tensor(2, shape=(), dtype=int32)


Real World Example 1: Face Unlock (Mobile Phone)

In [ ]:
# # Real World Example: Face Unlock

# Your Face

# ↓

# Camera Captures Image

# ↓

# Image Converted into Tensor

# ↓

# Deep Learning Model (CNN)

# ↓

# Face Recognition

# ↓

# Phone Unlocks

Aaj Humne Kya Sikha?

In [19]:
# ✔ TensorFlow

# ✔ Tensor

# ✔ Constant

# ✔ Variable

# ✔ Data Types

# ✔ Tensor Operations

# ✔ GPU Check

# ✔ Tensor Shape & Rank